name: Update README with GitHub Activity

on:
  schedule:
    # Runs at every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v1.1.0
        with:
          COMMIT_MSG: "Update README with recent activity"
      - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update README with recent activity"
          git push
